### ISSUE TITLE
Difference bw run_chat_server and run_chat_server_uvloop

### ISSUE THREAD

**Issue by dk5f95** [Bearle/django-private-chat#15]
I want to know difference bw run_chat_server and run_chat_server_uvloop. Is uvloop server  more faster than  run_chat_server ?????

**Comment by dk5f95** [comment]
**# when i use run_chat_server then it is working fine.But when i use run_chat_server_uvloop then it is showing me run time error.**

2018-03-17 01:40:19,440:INFO:Chat server started
17.03.18 01:40:19:INFO:Chat server started
17.03.18 01:40:19:ERROR:Task exception was never retrieved
future: <Task finished coro=<new_messages_handler() done, defined at /home/deepak/testing/chat/django_private_chat/handlers.py:117> exception=RuntimeError('Task <Task pending coro=<new_messages_handler() running at /home/deepak/testing/chat/django_private_chat/handlers.py:124>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/deepak/testing/chat/django_private_chat/handlers.py", line 124, in new_messages_handler
    packet = yield from stream.get()
  File "/usr/lib/python3.5/asyncio/queues.py", line 168, in get
    yield from getter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
RuntimeError: Task <Task pending coro=<new_messages_handler() running at /home/deepak/testing/chat/django_private_chat/handlers.py:124>> got Future <Future pending> attached to a different loop
17.03.18 01:40:19:ERROR:Task exception was never retrieved
future: <Task finished coro=<users_changed_handler() done, defined at /home/deepak/testing/chat/django_private_chat/handlers.py:168> exception=RuntimeError('Task <Task pending coro=<users_changed_handler() running at /home/deepak/testing/chat/django_private_chat/handlers.py:174>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/deepak/testing/chat/django_private_chat/handlers.py", line 174, in users_changed_handler
    yield from stream.get()
  File "/usr/lib/python3.5/asyncio/queues.py", line 168, in get
    yield from getter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
RuntimeError: Task <Task pending coro=<users_changed_handler() running at /home/deepak/testing/chat/django_private_chat/handlers.py:174>> got Future <Future pending> attached to a different loop
17.03.18 01:40:19:ERROR:Task exception was never retrieved
future: <Task finished coro=<gone_online() done, defined at /home/deepak/testing/chat/django_private_chat/handlers.py:39> exception=RuntimeError('Task <Task pending coro=<gone_online() running at /home/deepak/testing/chat/django_private_chat/handlers.py:45>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/deepak/testing/chat/django_private_chat/handlers.py", line 45, in gone_online
    packet = yield from stream.get()
  File "/usr/lib/python3.5/asyncio/queues.py", line 168, in get
    yield from getter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
RuntimeError: Task <Task pending coro=<gone_online() running at /home/deepak/testing/chat/django_private_chat/handlers.py:45>> got Future <Future pending> attached to a different loop
17.03.18 01:40:19:ERROR:Task exception was never retrieved
future: <Task finished coro=<check_online() done, defined at /home/deepak/testing/chat/django_private_chat/handlers.py:63> exception=RuntimeError('Task <Task pending coro=<check_online() running at /home/deepak/testing/chat/django_private_chat/handlers.py:69>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/deepak/testing/chat/django_private_chat/handlers.py", line 69, in check_online
    packet = yield from stream.get()
  File "/usr/lib/python3.5/asyncio/queues.py", line 168, in get
    yield from getter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
RuntimeError: Task <Task pending coro=<check_online() running at /home/deepak/testing/chat/django_private_chat/handlers.py:69>> got Future <Future pending> attached to a different loop
17.03.18 01:40:19:ERROR:Task exception was never retrieved
future: <Task finished coro=<gone_offline() done, defined at /home/deepak/testing/chat/django_private_chat/handlers.py:93> exception=RuntimeError('Task <Task pending coro=<gone_offline() running at /home/deepak/testing/chat/django_private_chat/handlers.py:99>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/deepak/testing/chat/django_private_chat/handlers.py", line 99, in gone_offline
    packet = yield from stream.get()
  File "/usr/lib/python3.5/asyncio/queues.py", line 168, in get
    yield from getter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
RuntimeError: Task <Task pending coro=<gone_offline() running at /home/deepak/testing/chat/django_private_chat/handlers.py:99>> got Future <Future pending> attached to a different loop
17.03.18 01:40:19:ERROR:Task exception was never retrieved
future: <Task finished coro=<is_typing_handler() done, defined at /home/deepak/testing/chat/django_private_chat/handlers.py:191> exception=RuntimeError('Task <Task pending coro=<is_typing_handler() running at /home/deepak/testing/chat/django_private_chat/handlers.py:197>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/deepak/testing/chat/django_private_chat/handlers.py", line 197, in is_typing_handler
    packet = yield from stream.get()
  File "/usr/lib/python3.5/asyncio/queues.py", line 168, in get
    yield from getter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
RuntimeError: Task <Task pending coro=<is_typing_handler() running at /home/deepak/testing/chat/django_private_chat/handlers.py:197>> got Future <Future pending> attached to a different loop
17.03.18 01:40:19:ERROR:Task exception was never retrieved
future: <Task finished coro=<read_message_handler() done, defined at /home/deepak/testing/chat/django_private_chat/handlers.py:214> exception=RuntimeError('Task <Task pending coro=<read_message_handler() running at /home/deepak/testing/chat/django_private_chat/handlers.py:220>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/deepak/testing/chat/django_private_chat/handlers.py", line 220, in read_message_handler
    packet = yield from stream.get()
  File "/usr/lib/python3.5/asyncio/queues.py", line 168, in get
    yield from getter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
RuntimeError: Task <Task pending coro=<read_message_handler() running at /home/deepak/testing/chat/django_private_chat/handlers.py:220>> got Future <Future pending> attached to a different loop

**Comment by dk5f95** [comment]
Anyone have any idea about this problem

**Comment by delneg** [comment]
uvloop is 2-4x faster than asyncio loops as said in the readme.
The error seems to be happening because of mixed usage of asyncio loop & uvloop loop, which leads to future being sent to wrong loop.
I don't really have the time right now to fix it, but if you want to give it a try, start with inspecting which loop futures run in and ensuring that all loops are retrieved using uvloop.new_event_loop() instead of  asyncio.get_event_loop()
