### ISSUE TITLE
Not support python 2.7.14

### ISSUE THREAD

**Issue by noahzaozao** [Bearle/django-private-chat#18]
* django-private-chat version: 0.1.8
* Django version: 1.10
* Python version: 2.7.14(pyenv)
* Operating System: Mac

### Description

Try to install this module with pip via python version 2.7.14, I know we have good support at python 3.5.x +, but I still want to confirm if it is possible to support python 2.7.x or not ?
Because many of the projects are using python 2.7.x. If it's possible , please let me know and I'll trying to make it work under 2.7.x.

### What I Did

```
$ pip install django-private-chat
Collecting django-private-chat
  Using cached https://files.pythonhosted.org/packages/aa/9a/07d932a75fde92b58f43cb487b47a9bbf0d53ccb5e0110133105558e60d4/django_private_chat-0.1.8-py2.py3-none-any.whl
Collecting django-braces>=1.10.0 (from django-private-chat)
  Using cached https://files.pythonhosted.org/packages/84/3c/fa2cca1411b456a84714efea8a2c805924eba6147e6b68e326caca9c7383/django_braces-1.13.0-py2.py3-none-any.whl
Collecting django-model-utils>=2.6.1 (from django-private-chat)
  Using cached https://files.pythonhosted.org/packages/d1/92/8a6b15368bb407f0a2e716bf603e73c843af782b98e68f23c19697742f8a/django_model_utils-3.1.2-py2.py3-none-any.whl
Collecting websockets==3.2 (from django-private-chat)
  Using cached https://files.pythonhosted.org/packages/c5/5c/fd5cbe294146421596459ba7ae55f39972d722e77da4c791fdc25be5c8e8/websockets-3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_0/5p_vjmhx4ygd40vvx0ndz1n00000gn/T/pip-install-hWDBY0/websockets/setup.py", line 19, in <module>
        with open(os.path.join(root, 'README'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_0/5p_vjmhx4ygd40vvx0ndz1n00000gn/T/pip-install-hWDBY0/websockets/
```

**Comment by delneg** [comment]
Asyncio is not supported in 2.7.
Do 2to3 after checking for https://github.com/brettcannon/caniusepython3, it's easy and just works.
P.S. please don't use 2.7 in 2018.
