### ISSUE TITLE
Deploying to Heroku. Unable to bind address.

### ISSUE THREAD

**Issue by MattBrown88** [Bearle/django-private-chat#57]
* django-private-chat version: 0.3.0
* Django version: 3.0.6
* Python version: 3.7

### Description

I'm trying to deploy an application with django-private-chat to Heroku. The chat works locally but I'm unable to get it to run after deployment

### What I Did
settings.py
```
# django-private-chat
CHAT_WS_SERVER_HOST = 'dealr-app.herokuapp.com'
CHAT_WS_SERVER_PORT = int(os.environ.get('PORT', 5002))
CHAT_WS_SERVER_PROTOCOL = 'wss'

os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true" 
```
Procfile
```
web: gunicorn dealr.wsgi
worker: python manage.py run_chat_server
```

worker logs
```
2020-05-21T13:56:59.203639+00:00 heroku[worker.1]: Restarting
2020-05-21T13:56:59.211261+00:00 heroku[worker.1]: State changed from up to starting
2020-05-21T13:57:06.801063+00:00 heroku[worker.1]: State changed from starting to up
2020-05-21T13:57:09.783249+00:00 app[worker.1]: 2020-05-21 13:57:09,783:INFO:Chat server started
2020-05-21T13:57:09.783304+00:00 app[worker.1]: 21.05.20 13:57:09:INFO:Chat server started
2020-05-21T13:57:09.795162+00:00 app[worker.1]: 21.05.20 13:57:09:ERROR:Task exception was never retrieved
2020-05-21T13:57:09.795163+00:00 app[worker.1]: future: <Task finished coro=<_wrap_awaitable() done, defined at /app/.heroku/python/lib/python3.6/asyncio/tasks.py:530> exception=OSError(99, "error while attempting to bind on address ('34.192.67.85', 28723): cannot assign requested address")>
2020-05-21T13:57:09.795164+00:00 app[worker.1]: Traceback (most recent call last):
2020-05-21T13:57:09.795164+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 1073, in create_server
2020-05-21T13:57:09.795165+00:00 app[worker.1]:     sock.bind(sa)
2020-05-21T13:57:09.795165+00:00 app[worker.1]: OSError: [Errno 99] Cannot assign requested address
2020-05-21T13:57:09.795166+00:00 app[worker.1]: 
2020-05-21T13:57:09.795181+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2020-05-21T13:57:09.795182+00:00 app[worker.1]: 
2020-05-21T13:57:09.795182+00:00 app[worker.1]: Traceback (most recent call last):
2020-05-21T13:57:09.795182+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
2020-05-21T13:57:09.795183+00:00 app[worker.1]:     return (yield from awaitable.__await__())
2020-05-21T13:57:09.795183+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/websockets/server.py", line 965, in __await_impl__
2020-05-21T13:57:09.795183+00:00 app[worker.1]:     server = await self._create_server()
2020-05-21T13:57:09.795184+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 1077, in create_server
2020-05-21T13:57:09.795184+00:00 app[worker.1]:     % (sa, err.strerror.lower()))
2020-05-21T13:57:09.795194+00:00 app[worker.1]: OSError: [Errno 99] error while attempting to bind on address ('34.192.67.85', 28723): cannot assign requested
```

**Comment by MattBrown88** [comment]
Realized this was a duplicate issue
