### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by kaustav1996** [Bearle/django-private-chat#7]
letest version!!

### Description
getting error when I
```
pip install -r requirements.txt
```
### What I Did

```
Using cached websockets-3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\kaust\appdata\local\temp\pip-build-848jcx\websockets\setup.py", line 19, in <module>
        with open(os.path.join(root, 'README'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by delneg** [comment]
Hi,
This problem is unrelated to this project.
You should review this issue:
https://github.com/aaugustin/websockets/issues/80
It's similar to what you've struggled into.
